create table Alert (
                       phase integer not null,
                       alert_id bigint generated by default as identity,
                       area varchar(255),
                       dateTime varchar(255),
                       primary key (alert_id)
)